# Generated by Django 5.2.17 on 2026-10-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GuidelineVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        editable=False, unique=True, verbose_name="버전"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="변경 메모"
                    ),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="활성")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                ("profile", models.TextField(blank=True, verbose_name="고정 정보")),
                (
                    "writing_rules",
                    models.TextField(blank=True, verbose_name="작성 규칙"),
                ),
                (
                    "output_format",
                    models.TextField(blank=True, verbose_name="요청 사항/출력 형식"),
                ),
                ("extra", models.TextField(blank=True, verbose_name="기타")),
            ],
            options={
                "verbose_name": "지침 버전",
                "verbose_name_plural": "지침 버전",
                "ordering": ["-version"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("is_active",),
                        name="unique_active_guideline_version",
                    )
                ],
            },
        ),
    ]
