# Generated by Django 5.2.17 on 2026-10-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="guidelineversion",
            name="privacy_checked",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="개인정보 점검 완료"
            ),
        ),
    ]
