# Generated by Django 5.2.17 on 2026-10-06 11:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="기업명"
                    ),
                ),
                (
                    "industry",
                    models.CharField(blank=True, max_length=100, verbose_name="업종"),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("startup", "스타트업"),
                            ("small", "중소"),
                            ("mid", "중견"),
                            ("large", "대기업"),
                        ],
                        max_length=20,
                        verbose_name="규모",
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="웹사이트")),
                ("memo", models.TextField(blank=True, verbose_name="메모")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name="삭제일시"
                    ),
                ),
            ],
            options={
                "verbose_name": "기업",
                "verbose_name_plural": "기업",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=200, verbose_name="직무명")),
                (
                    "posting_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="공고 URL"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("saramin", "사람인"),
                            ("jobkorea", "잡코리아"),
                            ("wanted", "원티드"),
                            ("jobplanet", "잡플래닛"),
                            ("linkedin", "링크드인"),
                            ("homepage", "회사 홈페이지"),
                            ("other", "기타"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="지원 경로",
                    ),
                ),
                ("main_tasks", models.TextField(blank=True, verbose_name="주요 업무")),
                (
                    "requirements",
                    models.TextField(blank=True, verbose_name="자격 요건"),
                ),
                ("preferred", models.TextField(blank=True, verbose_name="우대 사항")),
                (
                    "essay_char_limit",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="자소서 글자 수 제한"
                    ),
                ),
                (
                    "extra_notes",
                    models.TextField(blank=True, verbose_name="기타 공고 정보"),
                ),
                (
                    "deadline",
                    models.DateField(blank=True, null=True, verbose_name="마감일"),
                ),
                (
                    "applied_at",
                    models.DateField(blank=True, null=True, verbose_name="지원 완료일"),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("interest", "관심"),
                            ("applied", "지원 완료"),
                            ("document_passed", "서류 합격"),
                            ("test", "코딩테스트/과제"),
                            ("interview", "면접"),
                            ("final", "최종"),
                        ],
                        default="interest",
                        max_length=20,
                        verbose_name="진행 단계",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("in_progress", "진행 중"),
                            ("passed", "합격"),
                            ("failed", "불합격"),
                            ("withdrawn", "포기"),
                        ],
                        default="in_progress",
                        max_length=20,
                        verbose_name="결과",
                    ),
                ),
                (
                    "fit_score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="적합도 점수",
                    ),
                ),
                (
                    "fit_grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("high", "상"),
                            ("mid_high", "중상"),
                            ("mid", "중"),
                            ("mid_low", "중하"),
                            ("low", "하"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="적합도 등급",
                    ),
                ),
                ("memo", models.TextField(blank=True, verbose_name="메모")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "guideline_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applications",
                        to="profiles.guidelineversion",
                        verbose_name="분석에 사용한 지침 버전",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="applications.company",
                        verbose_name="기업",
                    ),
                ),
            ],
            options={
                "verbose_name": "지원 건",
                "verbose_name_plural": "지원 건",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_analysis",
                    models.TextField(blank=True, verbose_name="기업 분석"),
                ),
                (
                    "fit_evaluation",
                    models.TextField(blank=True, verbose_name="적합도 평가"),
                ),
                (
                    "motivation_draft",
                    models.TextField(blank=True, verbose_name="지원동기 초안"),
                ),
                (
                    "title_candidates",
                    models.TextField(blank=True, verbose_name="제목 후보"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "붙여넣기"), ("api", "API")],
                        default="manual",
                        max_length=10,
                        verbose_name="생성 방식",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="applications.application",
                        verbose_name="지원 건",
                    ),
                ),
            ],
            options={
                "verbose_name": "분석 결과",
                "verbose_name_plural": "분석 결과",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="StageHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("interest", "관심"),
                            ("applied", "지원 완료"),
                            ("document_passed", "서류 합격"),
                            ("test", "코딩테스트/과제"),
                            ("interview", "면접"),
                            ("final", "최종"),
                        ],
                        max_length=20,
                        verbose_name="이전 단계",
                    ),
                ),
                (
                    "to_stage",
                    models.CharField(
                        choices=[
                            ("interest", "관심"),
                            ("applied", "지원 완료"),
                            ("document_passed", "서류 합격"),
                            ("test", "코딩테스트/과제"),
                            ("interview", "면접"),
                            ("final", "최종"),
                        ],
                        max_length=20,
                        verbose_name="변경 단계",
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="변경일시"),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_history",
                        to="applications.application",
                        verbose_name="지원 건",
                    ),
                ),
            ],
            options={
                "verbose_name": "단계 변경 이력",
                "verbose_name_plural": "단계 변경 이력",
                "ordering": ["-changed_at", "-id"],
            },
        ),
    ]
