# Generated by Django 5.2.17 on 2026-10-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="source",
            field=models.CharField(
                choices=[
                    ("saramin", "사람인"),
                    ("jobkorea", "잡코리아"),
                    ("wanted", "원티드"),
                    ("jobplanet", "잡플래닛"),
                    ("linkedin", "링크드인"),
                    ("homepage", "회사 홈페이지"),
                    ("other", "기타"),
                ],
                default="saramin",
                max_length=20,
                verbose_name="지원 경로",
            ),
        ),
    ]
