# Generated by Django 5.2.17 on 2026-10-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_alter_application_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="review_notes",
            field=models.TextField(blank=True, verbose_name="검수 의견"),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="source",
            field=models.CharField(
                choices=[("manual", "붙여넣기"), ("api", "에이전트")],
                default="manual",
                max_length=10,
                verbose_name="생성 방식",
            ),
        ),
    ]
