# Generated by Django 5.2.17 on 2026-10-09 07:21

import applications.models
from django.db import migrations, models


# 그동안 코드(TextChoices)에 있던 선택지. (값, 이름) 순서대로 넣는다.
SOURCES = [
    ("saramin", "사람인"),
    ("jobkorea", "잡코리아"),
    ("wanted", "원티드"),
    ("jobplanet", "잡플래닛"),
    ("linkedin", "링크드인"),
    ("homepage", "회사 홈페이지"),
    ("other", "기타"),
]
STAGES = [
    ("interest", "관심"),
    ("applied", "지원 완료"),
    ("document_passed", "서류 합격"),
    ("test", "코딩테스트/과제"),
    ("interview", "면접"),
    ("final", "최종"),
]
RESULTS = [
    ("unread", "미열람"),
    ("read", "열람"),
    ("in_progress", "진행 중"),
    ("passed", "합격"),
    ("failed", "불합격"),
    ("withdrawn", "포기"),
]
SYSTEM = {("stage", "interest"), ("result", "unread"), ("result", "failed")}
OPEN_RESULTS = {"unread", "read", "in_progress"}
NO_RESPONSE_RESULTS = {"unread", "read"}


def seed_choices(apps, schema_editor):
    Choice = apps.get_model("applications", "Choice")
    for kind, items in (("source", SOURCES), ("stage", STAGES), ("result", RESULTS)):
        Choice.objects.bulk_create(
            Choice(
                kind=kind,
                value=value,
                label=label,
                order=order,
                is_system=(kind, value) in SYSTEM,
                is_open=kind == "result" and value in OPEN_RESULTS,
                is_no_response=kind == "result" and value in NO_RESPONSE_RESULTS,
            )
            for order, (value, label) in enumerate(items, start=1)
        )


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_analysis_review_notes_alter_analysis_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="result",
            field=models.CharField(
                default="unread", max_length=20, verbose_name="결과"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="source",
            field=models.CharField(
                default=applications.models.default_source,
                max_length=20,
                verbose_name="지원 경로",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="stage",
            field=models.CharField(
                default="interest", max_length=20, verbose_name="진행 단계"
            ),
        ),
        migrations.AlterField(
            model_name="stagehistory",
            name="from_stage",
            field=models.CharField(blank=True, max_length=20, verbose_name="이전 단계"),
        ),
        migrations.AlterField(
            model_name="stagehistory",
            name="to_stage",
            field=models.CharField(max_length=20, verbose_name="변경 단계"),
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("source", "지원 경로"),
                            ("stage", "진행 단계"),
                            ("result", "결과"),
                        ],
                        max_length=10,
                        verbose_name="종류",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True, editable=False, max_length=20, verbose_name="값"
                    ),
                ),
                ("label", models.CharField(max_length=30, verbose_name="이름")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="순서"
                    ),
                ),
                (
                    "is_hidden",
                    models.BooleanField(
                        default=False,
                        help_text="등록·수정 폼의 선택지에서 뺍니다. 이미 쓰고 있는 지원 건과 필터에는 남습니다.",
                        verbose_name="숨김",
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="시스템 값"
                    ),
                ),
                (
                    "is_open",
                    models.BooleanField(
                        default=False,
                        help_text="대시보드의 진행 중 건수와 마감 임박 알림에서 끝나지 않은 건으로 셉니다.",
                        verbose_name="아직 끝나지 않은 결과",
                    ),
                ),
                (
                    "is_no_response",
                    models.BooleanField(
                        default=False,
                        help_text="회사 쪽 반응이 아직 없는 결과입니다. 미응답 처리 모달에 나옵니다.",
                        verbose_name="미응답 처리 대상",
                    ),
                ),
            ],
            options={
                "verbose_name": "선택지",
                "verbose_name_plural": "선택지",
                "ordering": ["kind", "order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "value"), name="unique_choice_value"
                    ),
                    models.UniqueConstraint(
                        fields=("kind", "label"), name="unique_choice_label"
                    ),
                ],
            },
        ),
        migrations.RunPython(seed_choices, migrations.RunPython.noop),
    ]
