# Generated by Django 5.2.17 on 2026-10-07 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "0003_alter_application_result"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ocr", "공고 캡처 읽기"),
                            ("company_info", "기업 정보 검색"),
                            ("analysis", "기업 분석·적합도 평가"),
                        ],
                        max_length=20,
                        verbose_name="역할",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("claude", "Claude"), ("gemini", "Gemini")],
                        max_length=10,
                        verbose_name="AI",
                    ),
                ),
                ("model", models.CharField(max_length=50, verbose_name="모델")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "실행 중"),
                            ("succeeded", "완료"),
                            ("failed", "실패"),
                        ],
                        default="running",
                        max_length=10,
                        verbose_name="상태",
                    ),
                ),
                ("prompt", models.TextField(blank=True, verbose_name="입력")),
                (
                    "image_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="이미지 수"
                    ),
                ),
                ("output", models.TextField(blank=True, verbose_name="출력")),
                ("error", models.TextField(blank=True, verbose_name="오류")),
                (
                    "input_tokens",
                    models.PositiveIntegerField(default=0, verbose_name="입력 토큰"),
                ),
                (
                    "output_tokens",
                    models.PositiveIntegerField(default=0, verbose_name="출력 토큰"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="시작일시"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="종료일시"
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_runs",
                        to="applications.application",
                        verbose_name="지원 건",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_runs",
                        to="applications.company",
                        verbose_name="기업",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_runs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "에이전트 실행 기록",
                "verbose_name_plural": "에이전트 실행 기록",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AgentSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("claude", "Claude"), ("gemini", "Gemini")],
                        default="claude",
                        max_length=10,
                        verbose_name="사용할 AI",
                    ),
                ),
                (
                    "claude_model",
                    models.CharField(
                        choices=[
                            ("claude-opus-5-5", "Claude Opus 5.5 (가장 정확)"),
                            ("claude-sonnet-5-5", "Claude Sonnet 5.5 (절반 가격)"),
                            ("claude-haiku-4-5", "Claude Haiku 4.5 (가장 저렴)"),
                        ],
                        default="claude-opus-5-5",
                        max_length=50,
                        verbose_name="Claude 모델",
                    ),
                ),
                (
                    "gemini_model",
                    models.CharField(
                        default="gemini-2.5-flash",
                        max_length=50,
                        verbose_name="Gemini 모델",
                    ),
                ),
                (
                    "claude_api_key",
                    models.TextField(
                        blank=True, editable=False, verbose_name="Claude API 키(암호화)"
                    ),
                ),
                (
                    "gemini_api_key",
                    models.TextField(
                        blank=True, editable=False, verbose_name="Gemini API 키(암호화)"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "에이전트 설정",
                "verbose_name_plural": "에이전트 설정",
            },
        ),
    ]
