# Generated by Django 5.2.17 on 2026-10-07 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
        ("applications", "0004_analysis_review_notes_alter_analysis_source"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentrun",
            name="role",
            field=models.CharField(
                choices=[
                    ("ocr", "공고 캡처 읽기"),
                    ("research", "기업 조사"),
                    ("evaluate", "적합도 평가"),
                    ("write", "지원동기 작성"),
                    ("review", "검수"),
                ],
                max_length=20,
                verbose_name="역할",
            ),
        ),
        migrations.AlterField(
            model_name="agentsettings",
            name="gemini_model",
            field=models.CharField(
                default="gemini-3.5-flash-lite",
                max_length=50,
                verbose_name="Gemini 모델",
            ),
        ),
        migrations.CreateModel(
            name="AgentJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "실행 중"),
                            ("succeeded", "완료"),
                            ("failed", "실패"),
                        ],
                        default="running",
                        max_length=10,
                        verbose_name="상태",
                    ),
                ),
                (
                    "step",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ocr", "공고 캡처 읽기"),
                            ("research", "기업 조사"),
                            ("evaluate", "적합도 평가"),
                            ("write", "지원동기 작성"),
                            ("review", "검수"),
                        ],
                        max_length=20,
                        verbose_name="현재 단계",
                    ),
                ),
                (
                    "revisions",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="재작성 횟수"
                    ),
                ),
                ("error", models.TextField(blank=True, verbose_name="오류")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="시작일시"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="종료일시"
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_jobs",
                        to="applications.application",
                        verbose_name="지원 건",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "분석 작업",
                "verbose_name_plural": "분석 작업",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="agentrun",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="runs",
                to="agents.agentjob",
                verbose_name="분석 작업",
            ),
        ),
    ]
