# Generated by Django 5.2.17 on 2026-10-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "agents",
            "0002_alter_agentrun_role_alter_agentsettings_gemini_model_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="agentjob",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="마지막 진행일시"),
        ),
        migrations.AlterField(
            model_name="agentjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "실행 중"),
                    ("waiting", "확인 대기"),
                    ("succeeded", "완료"),
                    ("failed", "실패"),
                ],
                default="running",
                max_length=10,
                verbose_name="상태",
            ),
        ),
        migrations.AlterField(
            model_name="agentrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "실행 중"),
                    ("waiting", "확인 대기"),
                    ("succeeded", "완료"),
                    ("failed", "실패"),
                ],
                default="running",
                max_length=10,
                verbose_name="상태",
            ),
        ),
    ]
