# Generated by Django 5.2.17 on 2026-10-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0003_agentjob_updated_at_alter_agentjob_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentsettings",
            name="discord_webhook",
            field=models.TextField(
                blank=True, editable=False, verbose_name="디스코드 웹훅 주소(암호화)"
            ),
        ),
    ]
