# Generated by Django 5.2.17 on 2026-10-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0004_agentsettings_discord_webhook"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentjob",
            name="step",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ocr", "공고 캡처 읽기"),
                    ("research", "기업 조사"),
                    ("evaluate", "적합도 평가"),
                    ("write", "지원동기 작성"),
                    ("review", "검수"),
                    ("privacy", "개인정보 점검"),
                ],
                max_length=20,
                verbose_name="현재 단계",
            ),
        ),
        migrations.AlterField(
            model_name="agentrun",
            name="role",
            field=models.CharField(
                choices=[
                    ("ocr", "공고 캡처 읽기"),
                    ("research", "기업 조사"),
                    ("evaluate", "적합도 평가"),
                    ("write", "지원동기 작성"),
                    ("review", "검수"),
                    ("privacy", "개인정보 점검"),
                ],
                max_length=20,
                verbose_name="역할",
            ),
        ),
    ]
